# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20170515_1549'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixas',
            name='lancamentosId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.Lancamentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='contaBancariaId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cadastros.ContaBancaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='pendencia',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
