# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20170515_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='caixa',
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.CharField(max_length=3),
        ),
    ]
